language: generic
sudo: required

env:
  - SLUG=scalecube/enable-ci-cd-using-travis
  - SLUG=scalecube/scalecube-services

services:
- docker

install:
  docker build . --tag enable-ci-cd-using-travis
script:
  ./docker.run.sh
