language: generic
sudo: required

env:
  - SLUG=scalecube/scalecube-parent
  - SLUG=scalecube/scalecube-services
  - SLUG=scalecube/scalecube-security
  - SLUG=scalecube/scalecube-package-utils
  - SLUG=scalecube/scalecube-config
  - SLUG=scalecube/scalecube-benchmarks
  - SLUG=scalecube/scalecube-organization-service
  - SLUG=scalecube/scalecube-configuration-service
  - SLUG=scalecube/reactor-aeron
  - SLUG=scalecube/rsocket-transport-aeron
  - SLUG=scalecube/scalecube-test-utils
  - SLUG=scalecube/scalecube-cluster
  - SLUG=scalecube/scalecube-seed
  - SLUG=scalecube/trace-reporter
  - SLUG=scalecube/aeron-cluster-poc
  - SLUG=scalecube/scalecube-gateway
  - SLUG=scalecube/scalecube-commons
  - SLUG=scalecube/scalecube-spring-boot-starter
  - SLUG=scalecube/scalecube-vaultenv
install:
  docker build . --tag enable-ci-cd-using-travis
script:
  ./docker.run.sh
