language: generic
sudo: required

env:
  - SLUG=scalecube/scalecube-parent
  - SLUG=scalecube/scalecube-services
  - SLUG=scalecube/scalecube-gateway
  - SLUG=scalecube/scalecube-security
  - SLUG=scalecube/scalecube-app-utils
  - SLUG=scalecube/scalecube-config
  - SLUG=scalecube/scalecube-benchmarks
  - SLUG=scalecube/scalecube-organization-service
  - SLUG=scalecube/scalecube-configuration-service
  - SLUG=scalecube/reactor-aeron
install:
  docker build . --tag enable-ci-cd-using-travis
script:
  ./docker.run.sh
