language: generic
sudo: required

env:
  - SLUG=scalecube/scalecube-parent
  - SLUG=scalecube/scalecube-security
services:
- docker

install:
  docker build . --tag enable-ci-cd-using-travis
script:
  ./docker.run.sh
