language: generic
sudo: required

env:
  - SLUG=scalecube/scalecube-cluster
  - SLUG=scalecube/scalecube-security
  - SLUG=scalecube/config
  - SLUG=scalecube/scalecube-benchmarks
services:
- docker

install:
  docker build . --tag enable-ci-cd-using-travis
script:
  ./docker.run.sh
