deploy:
- provider: script
  script: mvn -P release deploy -DskipTests=true -B -V -s travis-settings.xml
  on:
    branch: develop
- provider: script
  script:
  - "./src/main/scripts/cd/deploy.sh"
  on:
    branch: master